name: Run Cypress tests for 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Start app and run Cypress tests
        run: npm run e2e:full

      - name: Upload testing reports
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/pipeline-workshop